### PR TITLE
Split json

### LINKED ISSUE #2: Convert JSON data to individual MQTT topics
Instead of publishing a monolithic JSON data topic, break out the individual properties to topics with their values.

Do this programmatically as to not require constant upkeep if the json changes

### PR DESCRIPTION
**Pull request by billchurch**
Convert JSON data to individual MQTT topics

Instead of publishing a monolithic JSON data topic, break out the individual properties to topics with their values.

Do this programmatically as to not require constant upkeep if the json changes

Also change "shit is sideways" to "API error" ;)

Fixes #2

### CODE REVIEW

**Comment by qbunt** [comment]
Hey @billchurch, good to hear you're a home-assistant nut too, this is why I put this together. What I'd propose is to define two separate modes (configurable via .env) to split the JSON into topic or send the object through verbatim. I totally understand the reluctance to send the full object through as it's quite large, but I could see some use-cases where it does make sense. Also, appreciate the expletive correction 🤣.

**Comment by qbunt** [comment]
I mean, I guess the alternative is to push the entire object through on a different topic, so you can just pick and choose?

**Comment by billchurch** [comment]
Let me re-work that and get on it.

**Comment by billchurch** [comment]
Okay, this should do what you're looking for, also added some documentation on the change. Default is your original behavior (true) whether or not the variable exists.

**Comment by billchurch** [comment]
Also, as an aside I'm working on a community addon for hassio, you can find that here: https://github.com/billchurch/addon-ambient-mqtt 

Right now it pulls from my repo since I'm basing it off this PR, but if this is accepted I'll switch your your repo

**Comment by qbunt** [comment]
Solid work man, thanks for the PR, keep me posted if you're interested in collaborating on the community addon

**Review by qbunt — APPROVED** [review]

**Comment by billchurch** [comment]
Definitely would like to collaborate. Take a look and tell me what you think, as soon as this repo is merged with that splitJSON branch I'll swing the addon-ambient-mqtt repo to reference your this repo for app source. https://github.com/billchurch/addon-ambient-mqtt

**Comment by qbunt** [comment]
Did this on mobile and assumed the merge happened, good to go!

**Pull request merged**
